core_vlans:
    - name: l3_core_vlan
      vlan_id: 200
      interface: Ethernet0/3

svi_interfaces:
    - name: vlan10
      ipv4: 10.1.10.0/24
      vrrp: yes
      ospf: passive
    - name: vlan20
      ipv4: 10.1.20.0/24
      vrrp: yes
      ospf: passive
    - name: vlan100
      ipv4: 10.1.100.0/24
      vrrp: yes
      ospf: passive

core_l3_links:
       core01:
           - name: GigabitEthernet0/0
             description: wan01_G1
             ipv4: 10.3.1.2 255.255.255.252
             ospf: yes
             ospf_metric: "100"
             peer: wan01
       core02:
           - name: GigabitEthernet0/0
             description: wan02_G1
             ipv4: 10.3.1.6 255.255.255.252
             ospf: yes
             ospf_metric: "200"
             peer: wan02

ospf_process: "20191"
ospf_area: "0"
