
interfaces:
    core01:
        - name: GigabitEthernet0/1
          description: access01_e0/1
          mode: trunk
        - name: GigabitEthernet0/2
          description: access02_e0/1
          mode: trunk
        - name: GigabitEthernet0/3
          description: core02_e0/3
          mode: trunk
    core02:
        - name: GigabitEthernet0/1
          description: access01_e0/2
          mode: trunk
        - name: GigabitEthernet0/2
          description: access02_e0/2
          mode: trunk
        - name: GigabitEthernet0/3
          description: core01_e0/3
          mode: trunk
    access01:
        - name: GigabitEthernet0/1
          description: core01_e0/1
          mode: trunk
        - name: GigabitEthernet0/2
          description: core02_e0/1
          mode: trunk
        - name: GigabitEthernet0/3
          description: Data_vlan
          mode: access
          vlan: 10
    access02:
        - name: GigabitEthernet0/1
          description: core01_e0/2
          mode: trunk
        - name: GigabitEthernet0/2
          description: core02_e0/2
          mode: trunk
        - name: GigabitEthernet0/0
          description: Data_vlan
          mode: access
          vlan: 20
        - name: GigabitEthernet0/3
          description: Data_vlan
          mode: access
          vlan: 10
vlans:
    - name: Data
      vlan_id: 10
    - name: Voice
      vlan_id: 20
    - name: Web
      vlan_id: 100
