
# Esta es la otra forma de estructurar los datos para la configuracion de interfaz en L3 y otros
interfaces:
    - port: "ge-0/0/0"
      ipv4_addr: "10.1.1.3/24"
      unit: 0
      peer: "mxp01"
      pport: "ge-0/0/0"
      peer_ip: "10.1.1.2"
    - port: "ge-0/0/1"
      ipv4_addr: "10.1.1.9/24"
      unit: 0
      peer: "mxp02"
      pport: "ge-0/0/0"
      peer_ip: "10.1.1.8"
