---
- name: Create config directory
  file: path={{config_dir}} state=directory
  run_once: yes

- name: Create temp directory per node
  file: path={{tmp_dir}}/{{inventory_hostname}} state=directory

- name: SEC FACT >> Build directory
  set_fact:
   build_dir: "{{tmp_dir}}/{{inventory_hostname}}"
