---
- name: "Build required directories"
  import_tasks: build_config_dir.yml

- name: "Build device configuration"
  import_tasks: build_device_config.yml

- name: "remove old assembled config"
  file:
      path: "{{config_dir}}/{{ inventory_hostname }}.cfg"
      state: absent

- name: "build final device configuration"
  assemble:
      src: "{{build_dir}}"
      dest: "{{config_dir}}/{{ inventory_hostname }}.cfg"

- name: "Remove build directory"
  file: path={{ tmp_dir }} state=absent
  run_once: yes
