---
 - name: "PLAY:1 THE CHAP-2 USE MODULE FACTS"
   hosts: core
   tasks:
       - name: "TASK:1 Collect device facts"
         ios_facts:
         register: device_facts

       - debug: var=device_facts

       - name: "TASK:2 Show a report with collect device"
         blockinfile:
             path: ./facts.yml
             create: yes
             block: |
               device_facts:
               {% for host in play_hosts %}
               {% set node = hostvars[host] %}
                 {{ node.ansible_net_hostname }}:
                     serial_number: {{ node.ansible_net_serialnum }}
                     ios_version: {{ node.ansible_net_version }}
               {% endfor %}
               all_loopbacks:
               {% for host in play_hosts %}
               {% set node = hostvars[host] %}
               {% if node.ansible_net_interfaces is defined %}
               {% if node.ansible_net_interfaces.Loopback0 is defined %}
                 - {{ node.ansible_net_interfaces.Loopback0.ipv4[0].address }}
               {% endif %}
               {% endif %}
               {% endfor %}
         run_once: yes
