---
 - name: "PLAY:1 Network Validation with pyATS"
   hosts: core
   roles:
       - Ansible-pyats
   vars:
       ansible_connection: local
   tasks:
       - pyats_parse_command:
           command: show ip ospf neighbor
         register: ospf_output
         vars:
             ansible_connection: network_cli

       - name: "FACT >> Pyats OSFP Info"
         set_fact:
             pyats_ospf_data: "{{ ospf_output.structured.interfaces }}"

       - name: "FACT >> set OSPF peers"
         set_fact:
             OSPF_PEERS: "{{ svi_interfaces | selectattr('ospf','equalto',true) | list }}"

       - name: "Validate Number of OSPF Peer"
         assert:
             that:
                 - pyats_ospf_data | length == OSPF_PEERS | length
         loop: "{{ OSPF_PEERS }}"

       - name: "task prueba"
         debug:
             msg: "{{ OSPF_PEERS }}"

       - name: "task prueba"
         debug:
             msg: "{{ pyats_ospf_data }}"

       - name: "Validate all peers are in FULL state"
         assert:
             that:
                 - pyats_ospf_data[item.name] | json_query('neighbor.*.state') | first == 'FULL/  -'
         loop: "{{ OSPF_PEERS }}"
