---
 - name: "PLAY:2 Configure VRRP L3 interfaces in core"
   hosts: core
   tasks:
       - name: "TASK:1 configure l3 interface"
         ios_l3_interface:
             name: "{{ item.name }}"
             ipv4: "{{ item.ipv4 | ipv4(hst_svi_id) }}"
         loop: "{{ svi_interfaces }}"


       - name: "TASK:2 Enable the Vlan Interfaces"
         ios_interfaces:
             config:
             - name: "{{ item.name }}"
               enabled: true
         loop: "{{ svi_interfaces }}"

       - name: "TASK:3 Create VRRP configs"
         ios_config:
             src: conf_vrrp.j2
